### ISSUE TITLE
06.ASN Worksheet

### ISSUE THREAD

**Issue by parthiban25** [astpl1998/logistics#15]

**Comment by parthiban25** [comment]
customer Name:Dvert_WMS_O0007

ASN   Worksheet
--




--

**Comment by parthiban25** [comment]
[6.Dvert_WMS_O0007_ASN Worksheet_V1 0.xlsx](https://github.com/murugananthaml/logistics/files/1878870/6.Dvert_WMS_O0007_ASN.Worksheet_V1.0.xlsx)

**Comment by murugeshkumar-T** [comment]
Here i have enclosed the asn work sheet out put file for your reference,
kindly check whether the data and format is correct.

**Comment by murugeshkumar-T** [comment]
[Report_26531018_a4b94f20-07d7-4f17-b412-7e9f7bd790b8.xlsx](https://github.com/murugananthaml/logistics/files/1931078/Report_26531018_a4b94f20-07d7-4f17-b412-7e9f7bd790b8.xlsx)

**Comment by parthiban25** [comment]
[ASN Format.xlsx](https://github.com/murugananthaml/logistics/files/1942365/ASN.Format.xlsx)
print is Generated but Data is not fetched the Report.
UAT server
https://vert.ramcouat.com/rvw/
user name:wmuser
password:wmuser18

Thanks
parthiban.R

**Comment by parthiban25** [comment]
[ASN worksheet.xlsx](https://github.cosm/murugananthaml/logistics/files/1942399/ASN.worksheet.xlsx)
Dear murugesh,
while multiple selection in line transaction system throw error "select atleast 1 ASN to Generate the Report"
UAT server
https://vert.ramcouat.com/rvw/
 user name:wmuser
 password:wmuser18

Thanks
 parthiban.R

**Comment by murugeshkumar-T** [comment]
In ASN Worksheet 
we are expecting below mentioned columns in base  (mentioned in pfs as new field) 
QA needed (Y/N)
GTP eligible (Y/N)
Case ID/SKU Barcode

**Comment by parthiban25** [comment]
Dear Devi,
Kindly resolve the issues
ASN Worksheet 
1.Status cancel should be Blank they required
2.multiple selection transaction should be Generated the Report
3.Report should be  in PDF Border is Truncated
4.Report header in center alignment & size increase
5.(Report Date) required date only  and remove Time
6.Date they Required Date only and remove Time
7.field 9 is Data fetching wrong (Case Level/SKU ASN)
8.field 10 is data fetching wrong(Case ID/SKU Barcode)
9.field 13 Dimensions Available? Data fetching wrong
10.header field is wrongly populated (QA needed(Y/N)?)
11.QA field is merging some other Data

**Comment by DeviAmitysoft** [comment]
4,5,6,7,10 points are complted in asn worksheet.
1,2,3,8,9,11 points are not yet completed

**Comment by murugeshkumar-T** [comment]
dear muruganantham, 

point number 2 , while launching multiple asn number in worksheet it will not preferring the worksheet  sp, it select format sp and throw the error 
kindly suggest the solution for this.

**Comment by murugeshkumar-T** [comment]
dear parthiban, 
in Asn worksheet except point number 2 ,remaining above mentioned issues are resolved,
have any other issues kindly let me know

**Comment by parthiban25** [comment]
Dear Murugeshkumar
Ramco Mentioned points,
Feedback on ASN Worksheet :- 

1.	Whenever ASN Selection is changed and Print Button is clicked, ASN Format report is getting launched even though Current Report on combo value is ‘ASN Worksheet’
2.	Font and Barcode Size needs to be increased. Row size can be increased for fitting barcodes.
3.	UID barcodes are getting merged for two UIDs. See against ASN000000263 both barcodes are getting merged. There should be space between two barcodes.
4.	QA needed(Y/N) logics are not working. For SKU level ASN it should be Yes but in below report it is showing as No. Check ASN000000262 and ASN000000264
5.	QA needed(Y/N) logics are not working. For mix UID it should be Yes but in below report it is showing as No. Check ASN000000265
Thanks & Regards
Parthiban.R

**Comment by murugeshkumar-T** [comment]
we made changes in design level, once latest objects is deployed all issues will be resolved

**Comment by parthiban25** [comment]
Dear Murugeshkumar,
Ramco team testing issues are highlighting 
.kindly conform whether it is  pending or closed
For ASN Worksheet
1.	Whenever ASN Selection is changed and Print Button is clicked, ASN Format report is getting launched even though Current Report on combo value is ‘ASN Worksheet’ – Not Fixed
2.	Font and Barcode Size needs to be increased. Row size can be increased for fitting barcodes. Not Fixed. Font and barcode size marked in yellow has to be increased. Fields Circled with red are not readable with the current Font
3.	UID barcodes are getting merged for two UIDs. See against ASN000000263 both barcodes are getting merged. There should be space between two barcodes. Fixed
4.	QA needed(Y/N) logics are not working. For SKU level ASN it should be Yes but in below report it is showing as No. Check ASN000000279. Not Fixed
5.	QA needed(Y/N) logics are not working. For mix UID it should be Yes but in below report it is showing as No. Check ASN000000280 Not Fixed
Thanks & Regards
Parthiban.R

**Comment by murugeshkumar-T** [comment]
Dear parthiban, 
point no1 is already completed in vert uat server 
point no 2 is modified in development server
point no 3,4 is need clarification

**Comment by parthiban25** [comment]
Dear murugeshkumar,
ASN Worksheet
As per customer Highlighted points modification is Done  
Kindly Deployed in UAT Server .Then only customer check and Feedback to given
Thanks & Regards,
parthiban.R

**Comment by murugeshkumar-T** [comment]
Dear parthiban 
ASN Worksheet objects are moved to vert uat server.

**Comment by parthiban25** [comment]
Dear Murugeshkumar,
Additional Requirement for ASN Worksheet as on 4-5-2018
Hi,

PFB updated Logic for QA Needed, Currently we are displaying ‘no’ even if 1 rule is dissatisfied and ‘yes’ only when all rules are satisfied now it is ‘Yes’ even if 1 Rule is satisfied and ‘No’ only when all Rules are dissatisfied. 
QA needed (Y/N)	ASN/Customer Master/Item Master	Will be derived from the mentioned rules	For 'No', all the below 6 rules should be dissatisfied  and QA Needed will be 'Yes', even if 1 Rule is satisfied
1. If Customer (seller) is marked as new in customer master 
2. If in item master, compliance field is filled with some data for the Item
3. If a case has multiple SKUs i.e. 1 UID serial number contains multiple item codes in ASN
4. If a pallet has multiple SKUs i.e. 1 THU serial number has multiple SKUs in ASN 
5. If it is a SKU level ASN (i.e) Check the SKU/Case Level ASN identification for SKU/Case Level ASN field
6. If Item dimensions (Length or Breadth or Height) are missing from item master	Item Master -> 'Compliance' Field Will be added in item master (New Field-available now in Item master)
Customer Master-> Marked as new(New Customer Check Box)->field - Will be added in customer master (New Field-Available now in Customer master)

New Customer Check Box in Customer Master for Rule 1 and Compliance Field in Item Master for Rule 2 are now available in System. 

Thanks & Regards
Parthiban.R

**Comment by nanda32** [comment]
Change login given on 08-05-2018 by(Gaurav)
GTP eligible (Y/N) | ASN | Item Code | If operation type is GTP then   populate it as Yes.   If operation type is Non-GTP then populate it as No | Operation type of the Item   ->field will be introduced in Item Master (new field)

**Comment by murugeshkumar-T** [comment]
Dear nandha
GTP eligible (Y/N) column is completed.

**Comment by murugeshkumar-T** [comment]
Dear parthiban 
in QA needed (Y/N) except point no 5 remaining points are completed.

**Comment by murugeshkumar-T** [comment]
Dear Team, 
in QA needed (Y/N) pont no 1 is completed
and point no 5 need clarification

**Comment by parthiban25** [comment]
Dear Murugesh & Murugantham,
Change request for New Development
ASN Worksheet ,
NEW Development
[Dvert_WMS_O0007_ASN Worksheet_V1 4.xlsx](https://github.com/murugananthaml/logistics/files/2110590/Dvert_WMS_O0007_ASN.Worksheet_V1.4.xlsx)

Thanks & Regards
Parthiban.R

**Comment by parthiban25** [comment]
hi murugesh,
testing issue
ASN Worksheet
[ASN Worksheet.xlsx](https://github.com/murugananthaml/logistics/files/2135748/ASN.Worksheet.xlsx)

thanks & regards
parthiban.R

**Comment by murugeshkumar-T** [comment]
[ASN worksheet.zip](https://github.com/astpl1998/logistics/files/2627923/ASN.worksheet.zip)

**Comment by raju-kurup** [comment]
Development completed
